### ISSUE TITLE
关于说mate70性能差的。

### ISSUE THREAD

**Issue by SkymontVibe** [XiaoBaiBZS/HangchengMemory#2]
芯片的设计成本之巨大是我们无可想像的，无数科研人员夜以继日研发的高新科技产品，被您一口否决，私以为这不是正确的。
如果您有能力设计出同等制程下性能更强大的芯片，这边希望您能在实验室里说出这句话
还是那句话，只看点200块钱就能解决，别骂江诗丹顿一天差2，3秒，没有可比性的

**Comment by XiaoBaiBZS** [comment]
？

**Comment by SkymontVibe** [comment]
串一串很开心[受虐滑稽]评论是从酷安热贴复制的

**Comment by XiaoBaiBZS** [comment]
以为被冲了。🤣

**Comment by XiaoBaiBZS** [comment]
我还以为GitHub都能吵起来。😂

**Comment by TheInterestingS0ul** [comment]
欢迎查看我的个人主页 @RewindBird 捏 😋
我就是超级节奏王，造假王，喜欢到处在别人的地盘上拉屎的Tis有趣的灵魂捏 🤣👉🤡
